// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-language'
  | 'pref-status-not-installed'
  | 'pref-status-ok'
  | 'pref-test-voice'
  | 'pref-title'
  | 'pref-voice';
